using CodeKb.Contracts;
using CodeKb.Scanner.Roslyn.Classification;
using FluentAssertions;
using Xunit;

namespace CodeKb.Scanner.Tests;

public class FileClassifierTests
{
    private readonly FileClassifier _c = new();

    [Theory]
    [InlineData("src/MyService.g.cs")]
    [InlineData("src/Form.Designer.cs")]
    [InlineData("obj/Debug/Thing.generated.cs")]
    [InlineData("project/generated/Out.cs")]
    public void Generated_DetectedByPath(string path)
        => _c.Classify(path, "").Should().Be(FileKind.Generated);

    [Fact]
    public void Generated_DetectedByAutoGeneratedComment()
        => _c.Classify("src/My.cs", "// <auto-generated />").Should().Be(FileKind.Generated);

    [Theory]
    [InlineData("appsettings.json")]
    [InlineData("config.yml")]
    [InlineData("settings.config")]
    [InlineData("Web.xml")]
    [InlineData(".env")]
    public void Config_DetectedByExtension(string path)
        => _c.Classify(path, "").Should().Be(FileKind.Configuration);

    [Fact]
    public void Config_DetectedByAppsettingsKeyword()
        => _c.Classify("src/appsettings.test.json", "").Should().Be(FileKind.Configuration);

    [Theory]
    [InlineData("tests/Foo.cs")]
    [InlineData("src/Acme.Tests/Bar.cs")]
    [InlineData("test/Foo.cs")]
    [InlineData("src/Service.Test/Foo.cs")]
    public void Test_DetectedByPath(string path)
        => _c.Classify(path, "").Should().Be(FileKind.Test);

    [Theory]
    [InlineData("[Fact]")]
    [InlineData("[Theory]")]
    [InlineData("[Test]")]
    [InlineData("[TestMethod]")]
    public void Test_DetectedByAttribute(string attr)
    {
        var content = $"class C {{ {attr} public void M() {{}} }}";
        _c.Classify("src/Foo.cs", content).Should().Be(FileKind.Test);
    }

    [Fact]
    public void Production_Default()
        => _c.Classify("src/Domain/Customer.cs", "namespace Domain { class Customer {} }").Should().Be(FileKind.Production);

    [Fact]
    public void Empty_RelativePath_Throws()
        => Assert.Throws<ArgumentException>(() => _c.Classify("", "x"));

    [Fact]
    public void BackslashPaths_Normalized()
        => _c.Classify("src\\test\\Foo.cs", "").Should().Be(FileKind.Test);

    [Fact]
    public void Generated_TakesPrecedenceOverConfig()
        => _c.Classify("appsettings.g.cs", "").Should().Be(FileKind.Generated);
}
