using CodeKb.Contracts;
using CodeKb.Scanner.Roslyn.Classification;
using FluentAssertions;
using Xunit;

namespace CodeKb.Scanner.Tests;

public class MoreFileClassifierTests
{
    [Fact]
    public void Static_IsTest_PathWithTestsSegment()
    {
        FileClassifier.IsTest("project/MyTests/Foo.cs", "").Should().BeTrue();
    }

    [Fact]
    public void Static_IsTest_NoMatchOutsideTestsSegment()
    {
        FileClassifier.IsTest("project/foo.cs", "").Should().BeFalse();
    }

    [Fact]
    public void Static_IsTest_ContentNullSafe()
    {
        FileClassifier.IsTest("foo.cs", "").Should().BeFalse();
    }

    [Fact]
    public void Static_IsGenerated_AutoGeneratedCaseInsensitive()
    {
        FileClassifier.IsGenerated("src/X.cs", "// <Auto-Generated />").Should().BeTrue();
    }

    [Fact]
    public void Static_IsConfig_FallsThroughOnUnknown()
    {
        FileClassifier.IsConfig("src/Foo.cs").Should().BeFalse();
    }
}
