using CodeKb.Contracts;

namespace CodeKb.Scanner.Roslyn.Classification;

public interface IFileClassifier
{
    FileKind Classify(string relativePath, string content);
}

public sealed class FileClassifier : IFileClassifier
{
    private static readonly string[] TestPathFragments = new[] { "/test/", "/tests/", ".Tests", ".Test", "test/", "tests/" };
    private static readonly string[] TestAttributes = new[] { "[Fact]", "[Theory]", "[Test]", "[TestMethod]" };

    private static readonly string[] GeneratedSuffixes = new[] { ".g.cs", ".Designer.cs", ".generated.cs" };

    private static readonly string[] ConfigExtensions = new[] { ".json", ".yaml", ".yml", ".config", ".xml", ".env" };

    public FileKind Classify(string relativePath, string content)
    {
        if (string.IsNullOrEmpty(relativePath))
            throw new ArgumentException("relativePath required", nameof(relativePath));

        var normalized = relativePath.Replace('\\', '/');

        if (IsGenerated(normalized, content))
            return FileKind.Generated;

        if (IsConfig(normalized))
            return FileKind.Configuration;

        if (IsTest(normalized, content))
            return FileKind.Test;

        return FileKind.Production;
    }

    public static bool IsGenerated(string path, string content)
    {
        foreach (var s in GeneratedSuffixes)
            if (path.EndsWith(s, StringComparison.OrdinalIgnoreCase)) return true;
        if (path.Contains("/generated/", StringComparison.OrdinalIgnoreCase)) return true;
        if (!string.IsNullOrEmpty(content) && content.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase))
            return true;
        return false;
    }

    public static bool IsConfig(string path)
    {
        var ext = Path.GetExtension(path);
        foreach (var e in ConfigExtensions)
            if (string.Equals(ext, e, StringComparison.OrdinalIgnoreCase)) return true;
        if (path.Contains("appsettings", StringComparison.OrdinalIgnoreCase)) return true;
        return false;
    }

    public static bool IsTest(string path, string content)
    {
        foreach (var frag in TestPathFragments)
            if (path.Contains(frag, StringComparison.OrdinalIgnoreCase)) return true;

        if (path.Contains("Tests", StringComparison.OrdinalIgnoreCase) && path.EndsWith(".cs", StringComparison.OrdinalIgnoreCase))
        {
            var parts = path.Split('/');
            foreach (var p in parts)
                if (p.IndexOf("Tests", StringComparison.OrdinalIgnoreCase) >= 0) return true;
        }

        if (!string.IsNullOrEmpty(content))
        {
            foreach (var attr in TestAttributes)
                if (content.Contains(attr, StringComparison.OrdinalIgnoreCase)) return true;
        }

        return false;
    }
}
